### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ufechner7** [aenarete/KiteSimulators.jl#20]
- [x] https://github.com/ufechner7/KiteModels.jl/issues/55 
- [x] https://github.com/ufechner7/KiteModels.jl/issues/57
- [ ] https://github.com/aenarete/AtmosphericModels.jl/issues/4
- [ ] https://github.com/aenarete/KiteSimulators.jl/issues/22
- [ ] https://github.com/ufechner7/KiteModels.jl/issues/58
- [ ] https://github.com/ufechner7/KiteModels.jl/issues/51
- [ ] https://github.com/aenarete/KiteControllers.jl/issues/22
- [ ] https://github.com/aenarete/KiteControllers.jl/issues/29
